// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reserve/collateral.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Collateral struct {
	Base             string                                  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Display          string                                  `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	MinimumDeposit   github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,3,opt,name=minimum_deposit,json=minimumDeposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"minimum_deposit"`
	MintingRatio     github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,4,opt,name=minting_ratio,json=mintingRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"minting_ratio"`
	LiquidationRatio github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,5,opt,name=liquidation_ratio,json=liquidationRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"liquidation_ratio"`
	InitTime         int64                                   `protobuf:"varint,6,opt,name=init_time,json=initTime,proto3" json:"init_time,omitempty"`
}

func (m *Collateral) Reset()         { *m = Collateral{} }
func (m *Collateral) String() string { return proto.CompactTextString(m) }
func (*Collateral) ProtoMessage()    {}
func (*Collateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_813e0280592e4b6c, []int{0}
}
func (m *Collateral) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Collateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Collateral.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Collateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collateral.Merge(m, src)
}
func (m *Collateral) XXX_Size() int {
	return m.Size()
}
func (m *Collateral) XXX_DiscardUnknown() {
	xxx_messageInfo_Collateral.DiscardUnknown(m)
}

var xxx_messageInfo_Collateral proto.InternalMessageInfo

func (m *Collateral) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Collateral) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Collateral) GetInitTime() int64 {
	if m != nil {
		return m.InitTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Collateral)(nil), "reserve.Collateral")
}

func init() { proto.RegisterFile("reserve/collateral.proto", fileDescriptor_813e0280592e4b6c) }

var fileDescriptor_813e0280592e4b6c = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd1, 0x4d, 0x4a, 0x03, 0x31,
	0x14, 0x07, 0xf0, 0x49, 0x5b, 0x5b, 0x1b, 0xfc, 0x0c, 0x82, 0x41, 0x21, 0x2d, 0x6e, 0xec, 0xc6,
	0x66, 0x21, 0x5e, 0xa0, 0xf5, 0x04, 0x43, 0x05, 0x11, 0xa1, 0x4c, 0x67, 0xc2, 0xf8, 0x70, 0x92,
	0x8c, 0x93, 0x8c, 0xd8, 0x5b, 0x78, 0x0c, 0x8f, 0xd2, 0x65, 0x97, 0xe2, 0xa2, 0xc8, 0x0c, 0xde,
	0x43, 0xe6, 0x4b, 0xdc, 0xea, 0x2a, 0xef, 0xfd, 0x5f, 0xf2, 0xcb, 0xe2, 0x61, 0x9a, 0x08, 0x23,
	0x92, 0x67, 0xc1, 0x7d, 0x1d, 0x45, 0x9e, 0x15, 0x89, 0x17, 0x8d, 0xe3, 0x44, 0x5b, 0x4d, 0x7a,
	0xf5, 0xe4, 0xe4, 0x28, 0xd4, 0xa1, 0x2e, 0x33, 0x5e, 0x54, 0xd5, 0xf8, 0xec, 0xab, 0x85, 0xf1,
	0xf4, 0xe7, 0x0d, 0x21, 0xb8, 0xb3, 0xf0, 0x8c, 0xa0, 0x68, 0x88, 0x46, 0x7d, 0xb7, 0xac, 0x09,
	0xc5, 0xbd, 0x00, 0x4c, 0x1c, 0x79, 0x4b, 0xda, 0x2a, 0xe3, 0xa6, 0x25, 0xb7, 0x78, 0x5f, 0x82,
	0x02, 0x99, 0xca, 0x79, 0x20, 0x62, 0x6d, 0xc0, 0xd2, 0x76, 0x71, 0x63, 0xc2, 0x57, 0x9b, 0x81,
	0xf3, 0xb1, 0x19, 0x9c, 0x87, 0x60, 0x1f, 0xd2, 0xc5, 0xd8, 0xd7, 0x92, 0xfb, 0xda, 0x48, 0x6d,
	0xea, 0xe3, 0xc2, 0x04, 0x8f, 0xdc, 0x2e, 0x63, 0x61, 0xc6, 0x53, 0x0d, 0xca, 0xdd, 0xab, 0x9d,
	0xeb, 0x8a, 0x21, 0x33, 0xbc, 0x2b, 0x41, 0x59, 0x50, 0xe1, 0x3c, 0xf1, 0x2c, 0x68, 0xda, 0xf9,
	0xb3, 0x7b, 0x03, 0xca, 0xba, 0x3b, 0xb5, 0xe2, 0x16, 0x08, 0xb9, 0xc7, 0x87, 0x11, 0x3c, 0xa5,
	0x10, 0x14, 0x9d, 0xaa, 0xe5, 0xad, 0xff, 0xc9, 0x07, 0xbf, 0xa4, 0x4a, 0x3f, 0xc5, 0x7d, 0x50,
	0x60, 0xe7, 0x16, 0xa4, 0xa0, 0xdd, 0x21, 0x1a, 0xb5, 0xdd, 0xed, 0x22, 0x98, 0x81, 0x14, 0x93,
	0xab, 0xb7, 0x8c, 0xa1, 0x55, 0xc6, 0xd0, 0x3a, 0x63, 0xe8, 0x33, 0x63, 0xe8, 0x35, 0x67, 0xce,
	0x3a, 0x67, 0xce, 0x7b, 0xce, 0x9c, 0xbb, 0xe3, 0x66, 0x7d, 0x2f, 0xbc, 0xa9, 0xca, 0xaf, 0x16,
	0xdd, 0x72, 0x4b, 0x97, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xa6, 0x30, 0x00, 0xe0, 0x01,
	0x00, 0x00,
}

func (this *Collateral) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Collateral)
	if !ok {
		that2, ok := that.(Collateral)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Base != that1.Base {
		return false
	}
	if this.Display != that1.Display {
		return false
	}
	if !this.MinimumDeposit.Equal(that1.MinimumDeposit) {
		return false
	}
	if !this.MintingRatio.Equal(that1.MintingRatio) {
		return false
	}
	if !this.LiquidationRatio.Equal(that1.LiquidationRatio) {
		return false
	}
	if this.InitTime != that1.InitTime {
		return false
	}
	return true
}
func (m *Collateral) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Collateral) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Collateral) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InitTime != 0 {
		i = encodeVarintCollateral(dAtA, i, uint64(m.InitTime))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.LiquidationRatio.Size()
		i -= size
		if _, err := m.LiquidationRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollateral(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MintingRatio.Size()
		i -= size
		if _, err := m.MintingRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollateral(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinimumDeposit.Size()
		i -= size
		if _, err := m.MinimumDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintCollateral(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Display) > 0 {
		i -= len(m.Display)
		copy(dAtA[i:], m.Display)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.Display)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Base) > 0 {
		i -= len(m.Base)
		copy(dAtA[i:], m.Base)
		i = encodeVarintCollateral(dAtA, i, uint64(len(m.Base)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCollateral(dAtA []byte, offset int, v uint64) int {
	offset -= sovCollateral(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Collateral) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Base)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	l = len(m.Display)
	if l > 0 {
		n += 1 + l + sovCollateral(uint64(l))
	}
	l = m.MinimumDeposit.Size()
	n += 1 + l + sovCollateral(uint64(l))
	l = m.MintingRatio.Size()
	n += 1 + l + sovCollateral(uint64(l))
	l = m.LiquidationRatio.Size()
	n += 1 + l + sovCollateral(uint64(l))
	if m.InitTime != 0 {
		n += 1 + sovCollateral(uint64(m.InitTime))
	}
	return n
}

func sovCollateral(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCollateral(x uint64) (n int) {
	return sovCollateral(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Collateral) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCollateral
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Collateral: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Collateral: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Base", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Base = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Display", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Display = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintingRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintingRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCollateral
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCollateral
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidationRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitTime", wireType)
			}
			m.InitTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCollateral(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCollateral
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCollateral(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCollateral
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCollateral
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCollateral
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCollateral
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCollateral
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCollateral        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCollateral          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCollateral = fmt.Errorf("proto: unexpected end of group")
)
