// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: reserve/proposal.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/x/bank/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// CreateDenomProposal details a create-denom proposal.
type CreateDenomProposal struct {
	Sender            string                                    `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Title             string                                    `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description       string                                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DenomMetadata     *types.Metadata                           `protobuf:"bytes,4,opt,name=denom_metadata,json=denomMetadata,proto3" json:"denom_metadata,omitempty"`
	BondMetadata      *types.Metadata                           `protobuf:"bytes,5,opt,name=bond_metadata,json=bondMetadata,proto3" json:"bond_metadata,omitempty"`
	ExchangeRate      []github_com_cosmos_cosmos_sdk_types.Uint `protobuf:"bytes,6,rep,name=exchange_rate,json=exchangeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"exchange_rate"`
	CollateralDeposit github_com_cosmos_cosmos_sdk_types.Coin   `protobuf:"bytes,7,opt,name=collateral_deposit,json=collateralDeposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"collateral_deposit"`
	DebtInterestRate  uint64                                    `protobuf:"varint,8,opt,name=debt_interest_rate,json=debtInterestRate,proto3" json:"debt_interest_rate,omitempty"`
	// Negative Interest rate on Denoms Bonded
	BondInterestRate uint64 `protobuf:"varint,9,opt,name=bond_interest_rate,json=bondInterestRate,proto3" json:"bond_interest_rate,omitempty"`
}

func (m *CreateDenomProposal) Reset()         { *m = CreateDenomProposal{} }
func (m *CreateDenomProposal) String() string { return proto.CompactTextString(m) }
func (*CreateDenomProposal) ProtoMessage()    {}
func (*CreateDenomProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_179ea2155667c8d4, []int{0}
}
func (m *CreateDenomProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateDenomProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateDenomProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateDenomProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDenomProposal.Merge(m, src)
}
func (m *CreateDenomProposal) XXX_Size() int {
	return m.Size()
}
func (m *CreateDenomProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDenomProposal.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDenomProposal proto.InternalMessageInfo

// RegisterCollateralProposal details a register-collateral proposal.
type RegisterCollateralProposal struct {
	Sender           string                                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Title            string                                  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description      string                                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Metadata         *types.Metadata                         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	MinimumDeposit   github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=minimum_deposit,json=minimumDeposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"minimum_deposit"`
	LendingRatio     uint64                                  `protobuf:"varint,6,opt,name=lending_ratio,json=lendingRatio,proto3" json:"lending_ratio,omitempty"`
	LiquidationRatio uint64                                  `protobuf:"varint,7,opt,name=liquidation_ratio,json=liquidationRatio,proto3" json:"liquidation_ratio,omitempty"`
}

func (m *RegisterCollateralProposal) Reset()         { *m = RegisterCollateralProposal{} }
func (m *RegisterCollateralProposal) String() string { return proto.CompactTextString(m) }
func (*RegisterCollateralProposal) ProtoMessage()    {}
func (*RegisterCollateralProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_179ea2155667c8d4, []int{1}
}
func (m *RegisterCollateralProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterCollateralProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterCollateralProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterCollateralProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterCollateralProposal.Merge(m, src)
}
func (m *RegisterCollateralProposal) XXX_Size() int {
	return m.Size()
}
func (m *RegisterCollateralProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterCollateralProposal.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterCollateralProposal proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateDenomProposal)(nil), "reserve.CreateDenomProposal")
	proto.RegisterType((*RegisterCollateralProposal)(nil), "reserve.RegisterCollateralProposal")
}

func init() { proto.RegisterFile("reserve/proposal.proto", fileDescriptor_179ea2155667c8d4) }

var fileDescriptor_179ea2155667c8d4 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x4f, 0x6b, 0x13, 0x41,
	0x1c, 0xdd, 0x6d, 0xf3, 0x77, 0x9a, 0x54, 0x3b, 0x96, 0xba, 0x04, 0xdc, 0x84, 0x7a, 0x30, 0x60,
	0xdd, 0xa5, 0x8a, 0x07, 0x3d, 0x26, 0xb9, 0x78, 0x10, 0x64, 0x51, 0x10, 0x0f, 0x86, 0xd9, 0xcc,
	0x8f, 0xed, 0xd0, 0xdd, 0x99, 0x75, 0x66, 0x52, 0xea, 0x37, 0x10, 0xbc, 0xf8, 0x11, 0x7a, 0xf4,
	0xa3, 0xf4, 0xd8, 0xa3, 0x08, 0x16, 0x49, 0x2e, 0x7e, 0x0c, 0xd9, 0xd9, 0xd9, 0x24, 0xde, 0xac,
	0xe0, 0x69, 0xe7, 0xf7, 0xde, 0x9b, 0xb7, 0x8f, 0xc7, 0xfc, 0xd0, 0x81, 0x04, 0x05, 0xf2, 0x0c,
	0xc2, 0x5c, 0x8a, 0x5c, 0x28, 0x92, 0x06, 0xb9, 0x14, 0x5a, 0xe0, 0xa6, 0xc5, 0x7b, 0xfb, 0x89,
	0x48, 0x84, 0xc1, 0xc2, 0xe2, 0x54, 0xd2, 0x3d, 0x7f, 0x26, 0x54, 0x26, 0x54, 0x18, 0x13, 0x7e,
	0x1a, 0x9e, 0x1d, 0xc7, 0xa0, 0xc9, 0xb1, 0x19, 0x4a, 0xfe, 0xf0, 0x73, 0x0d, 0xdd, 0x19, 0x4b,
	0x20, 0x1a, 0x26, 0xc0, 0x45, 0xf6, 0xca, 0x9a, 0xe3, 0x03, 0xd4, 0x50, 0xc0, 0x29, 0x48, 0xcf,
	0x1d, 0xb8, 0xc3, 0x76, 0x64, 0x27, 0xbc, 0x8f, 0xea, 0x9a, 0xe9, 0x14, 0xbc, 0x2d, 0x03, 0x97,
	0x03, 0x1e, 0xa0, 0x1d, 0x0a, 0x6a, 0x26, 0x59, 0xae, 0x99, 0xe0, 0xde, 0xb6, 0xe1, 0x36, 0x21,
	0x3c, 0x41, 0xbb, 0xb4, 0xf8, 0xc1, 0x34, 0x03, 0x4d, 0x28, 0xd1, 0xc4, 0xab, 0x0d, 0xdc, 0xe1,
	0xce, 0xe3, 0x7b, 0x41, 0x19, 0x30, 0x30, 0x99, 0x6c, 0xc0, 0xe0, 0xa5, 0x15, 0x45, 0x5d, 0x73,
	0xa9, 0x1a, 0xf1, 0x08, 0x75, 0x63, 0xc1, 0xe9, 0xda, 0xa4, 0xfe, 0x37, 0x26, 0x9d, 0xe2, 0xce,
	0xca, 0xe3, 0x35, 0xea, 0xc2, 0xf9, 0xec, 0x84, 0xf0, 0x04, 0xa6, 0x92, 0x68, 0xf0, 0x1a, 0x83,
	0xed, 0x61, 0x7b, 0x14, 0x5e, 0x5e, 0xf7, 0x9d, 0xef, 0xd7, 0xfd, 0x07, 0x09, 0xd3, 0x27, 0xf3,
	0x38, 0x98, 0x89, 0x2c, 0xb4, 0xdd, 0x95, 0x9f, 0x47, 0x8a, 0x9e, 0x86, 0xfa, 0x63, 0x0e, 0x2a,
	0x78, 0xc3, 0xb8, 0x8e, 0x3a, 0x95, 0x4b, 0x44, 0x34, 0xe0, 0xf7, 0x08, 0xcf, 0x44, 0x9a, 0x12,
	0x0d, 0x92, 0xa4, 0x53, 0x0a, 0xb9, 0x50, 0x4c, 0x7b, 0xcd, 0xa2, 0x88, 0x1b, 0x59, 0x8f, 0x05,
	0xe3, 0xd1, 0xde, 0xda, 0x6a, 0x52, 0x3a, 0xe1, 0x23, 0x84, 0x29, 0xc4, 0x7a, 0xca, 0xb8, 0x06,
	0x09, 0x4a, 0x97, 0xd1, 0x5b, 0x03, 0x77, 0x58, 0x8b, 0x6e, 0x17, 0xcc, 0x0b, 0x4b, 0x98, 0x34,
	0x47, 0x08, 0x9b, 0x9e, 0xfe, 0x54, 0xb7, 0x4b, 0x75, 0xc1, 0x6c, 0xaa, 0x9f, 0xb7, 0x3e, 0x5d,
	0xf4, 0x9d, 0x5f, 0x17, 0x7d, 0xe7, 0xf0, 0xc7, 0x16, 0xea, 0x45, 0x90, 0x30, 0xa5, 0x41, 0x8e,
	0x57, 0x19, 0xfe, 0xdb, 0xa3, 0x78, 0x86, 0x5a, 0x37, 0x7b, 0x0e, 0x2b, 0x39, 0x7e, 0x8b, 0x6e,
	0x65, 0x8c, 0xb3, 0x6c, 0x9e, 0xad, 0xca, 0xae, 0xff, 0x5b, 0xd9, 0xbb, 0xd6, 0xa7, 0x6a, 0xfa,
	0x3e, 0xea, 0xa6, 0xc0, 0x29, 0xe3, 0x49, 0xd1, 0x1a, 0x13, 0x5e, 0xc3, 0xd4, 0xd6, 0xb1, 0x60,
	0x54, 0x60, 0xf8, 0x21, 0xda, 0x4b, 0xd9, 0x87, 0x39, 0xa3, 0xc5, 0xc4, 0xad, 0xb0, 0x59, 0xf6,
	0xbb, 0x41, 0x18, 0xf1, 0xba, 0xdf, 0xd1, 0xd3, 0xaf, 0x0b, 0xdf, 0xbd, 0x5c, 0xf8, 0xee, 0xd5,
	0xc2, 0x77, 0x7f, 0x2e, 0x7c, 0xf7, 0xcb, 0xd2, 0x77, 0xae, 0x96, 0xbe, 0xf3, 0x6d, 0xe9, 0x3b,
	0xef, 0xee, 0x56, 0x2b, 0x7e, 0x1e, 0x56, 0x27, 0x93, 0x33, 0x6e, 0x98, 0x5d, 0x7d, 0xf2, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0x83, 0xa4, 0x33, 0x82, 0x04, 0x04, 0x00, 0x00,
}

func (m *CreateDenomProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateDenomProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateDenomProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BondInterestRate != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.BondInterestRate))
		i--
		dAtA[i] = 0x48
	}
	if m.DebtInterestRate != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.DebtInterestRate))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.CollateralDeposit.Size()
		i -= size
		if _, err := m.CollateralDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.ExchangeRate) > 0 {
		for iNdEx := len(m.ExchangeRate) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.ExchangeRate[iNdEx].Size()
				i -= size
				if _, err := m.ExchangeRate[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintProposal(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.BondMetadata != nil {
		{
			size, err := m.BondMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProposal(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.DenomMetadata != nil {
		{
			size, err := m.DenomMetadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProposal(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterCollateralProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterCollateralProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterCollateralProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LiquidationRatio != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.LiquidationRatio))
		i--
		dAtA[i] = 0x38
	}
	if m.LendingRatio != 0 {
		i = encodeVarintProposal(dAtA, i, uint64(m.LendingRatio))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.MinimumDeposit.Size()
		i -= size
		if _, err := m.MinimumDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintProposal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProposal(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintProposal(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProposal(dAtA []byte, offset int, v uint64) int {
	offset -= sovProposal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreateDenomProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	if m.DenomMetadata != nil {
		l = m.DenomMetadata.Size()
		n += 1 + l + sovProposal(uint64(l))
	}
	if m.BondMetadata != nil {
		l = m.BondMetadata.Size()
		n += 1 + l + sovProposal(uint64(l))
	}
	if len(m.ExchangeRate) > 0 {
		for _, e := range m.ExchangeRate {
			l = e.Size()
			n += 1 + l + sovProposal(uint64(l))
		}
	}
	l = m.CollateralDeposit.Size()
	n += 1 + l + sovProposal(uint64(l))
	if m.DebtInterestRate != 0 {
		n += 1 + sovProposal(uint64(m.DebtInterestRate))
	}
	if m.BondInterestRate != 0 {
		n += 1 + sovProposal(uint64(m.BondInterestRate))
	}
	return n
}

func (m *RegisterCollateralProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovProposal(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovProposal(uint64(l))
	}
	l = m.MinimumDeposit.Size()
	n += 1 + l + sovProposal(uint64(l))
	if m.LendingRatio != 0 {
		n += 1 + sovProposal(uint64(m.LendingRatio))
	}
	if m.LiquidationRatio != 0 {
		n += 1 + sovProposal(uint64(m.LiquidationRatio))
	}
	return n
}

func sovProposal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProposal(x uint64) (n int) {
	return sovProposal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreateDenomProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateDenomProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateDenomProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DenomMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DenomMetadata == nil {
				m.DenomMetadata = &types.Metadata{}
			}
			if err := m.DenomMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BondMetadata == nil {
				m.BondMetadata = &types.Metadata{}
			}
			if err := m.BondMetadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Uint
			m.ExchangeRate = append(m.ExchangeRate, v)
			if err := m.ExchangeRate[len(m.ExchangeRate)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollateralDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DebtInterestRate", wireType)
			}
			m.DebtInterestRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DebtInterestRate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondInterestRate", wireType)
			}
			m.BondInterestRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondInterestRate |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterCollateralProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterCollateralProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterCollateralProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &types.Metadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProposal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProposal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LendingRatio", wireType)
			}
			m.LendingRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LendingRatio |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationRatio", wireType)
			}
			m.LiquidationRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationRatio |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProposal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProposal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProposal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProposal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProposal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProposal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProposal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProposal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProposal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProposal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProposal = fmt.Errorf("proto: unexpected end of group")
)
